/// dcli script generated by:
/// dcli create docker_push.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///
///
///import 'dart:io';

import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:dcli/dcli.dart';

import '../env_file.dart';
import '../unpubd_paths.dart';
import '../unpubd_settings.dart';
import '../util/log.dart';

///
class UpCommand extends Command<void> {
  ///
  UpCommand() {
    argParser.addFlag('detached',
        abbr: 'd', help: 'Start unpubd as a background daemon');
  }

  @override
  String get description => 'Starts the unpubd daemon.';

  @override
  String get name => 'up';

  @override
  void run() {
    UnpubdSettings.load();

    if (!exists(UnpubdSettings.pathToSettings)) {
      logerr(red('''You must run 'unpubd install' first.'''));
      exit(1);
    }

    final detached = argResults!['detached'] as bool;
    up(detached: detached);
  }

  ///
  void up({required bool detached}) {
    EnvFile.create();
    start(detached: detached);
  }

  Future<void> start({required bool detached}) async {
    EnvFile.create();
    print('Starting unpubd');
    final detachedArg = detached ? '--detached' : '';

    'docker-compose up $detachedArg'
        .start(workingDirectory: dirname(UnpubdPaths().pathToDockerCompose));
  }
}
